<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT1s6j1V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT1s6j1V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT1s6j1V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT1s6j1V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT1s6j1V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T1s6j1V',
    'container.build_id' => 'ebb57913',
    'container.build_time' => 1591382486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT1s6j1V');
